// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sirupsen/logrus"
	
	"recommendation-system/internal/datacollection"
	"recommendation-system/internal/dataprocessing"
	"recommendation-system/internal/domain"
	"recommendation-system/internal/infra/config"
	"recommendation-system/internal/recommendation"
)

// NewLogger 创建日志记录器
func NewLogger() *logrus.Logger {
	logger := logrus.New()
	logger.SetFormatter(&logrus.JSONFormatter{})
	return logger
}

// Application 应用程序容器
type Application struct {
	ConfigManager      config.ConfigManager
	RecommendationSvc  domain.RecommendationService
	Logger            *logrus.Logger
}

// InitializeApp 初始化应用程序
func InitializeApp() (*Application, error) {
	logger := NewLogger()
	configManager := config.NewViperConfigManager()
	dataCollector := datacollection.NewMemoryDataCollector(logger)
	dataProcessor := dataprocessing.NewMemoryDataProcessor(logger)
	recommendationEngine := recommendation.NewRecommendationEngine(logger, dataCollector, dataProcessor, nil, nil, nil)
	app := &Application{
		ConfigManager:     configManager,
		RecommendationSvc: recommendationEngine,
		Logger:           logger,
	}
	return app, nil
}